### ISSUE TITLE
Kallisto quantification fails to execute

### ISSUE THREAD

**Issue by Mintxoklet** [GuyTeichman/RNAlysis#14]
* sRNA analysis pipeline version: 3.6.2
* Python version: 3.10.9
* Operating System: Windows

### Description

I have used RNAlysis before, I was just trying to use the kallisto gene quantification tool for 8 paired end read fastq samplles, but when starting the quant a message error appears.

```
Traceback (most recent call last):
  File "rnalysis\gui\gui.py", line 3662, in finish_generic_job
  File "rnalysis\gui\gui_widgets.py", line 329, in run
  File "rnalysis\fastq.py", line 850, in kallisto_quantify_paired_end
  File "rnalysis\fastq.py", line 898, in _parse_kallisto_misc_args
  File "rnalysis\utils\io.py", line 1459, in generate_base_call
  File "rnalysis\utils\io.py", line 1400, in run_subprocess
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
OSError: [WinError 193] %1 no es una aplicación Win32 válida


```
What could be causing the issue?

**Comment by GuyTeichman** [comment]
Hi, 
It appears like RNAlysis fails to find the kallisto executable. 
I have a few follow-up questions:
1. Did you specify the installation folder of kallisto? If so, what's the path you specified?
2. Are you using the RNAlysis stand-alone app or installed via Python?

Thanks,
Guy.

**Comment by Mintxoklet** [comment]
Hello, 
So first I tried with the RNAlysis version 3.4 I had installed with Python. And that ocurred. When initializing RNAlysis it told me there was a newer verions available (3.6) but for some reason when trying to update, the app would just close and restart again, asking once more if I would like to update. So I tried updating it by downloading the standalone zip 3.6 version and executing it with the RNAlysis.exe as stated in the instructions. This way I had 2 rnalysis. I tried then using the 3.6 version, but the error prompt when performing the kallisto quantification was exactly the same.

Regarding question 1, I specified the kallisto folder which was "C:\Users\Jon\AppData\Local\kallisto". For instance RNalysis folder is in that same "Local" directory, if that is of any use to you.

**Comment by GuyTeichman** [comment]
Hi,
Could you please make sure that inside the folder "C:\Users\Jon\AppData\Local\kallisto" exists a file called "kallisto.exe"?

**Comment by GuyTeichman** [comment]
Hi,
Could you please make sure that inside the folder "C:\Users\Jon\AppData\Local\kallisto" exists a file called "kallisto.exe"?

**Comment by Mintxoklet** [comment]
Hello again,
The manual pip update worked just fine to update to the latest 3.6.2 version.
However, the error I got when trying to perform the kallisto quantification was exactly the same. 
:(
