### ISSUE TITLE
No such file or directory: latest_version.txt

### ISSUE THREAD

**Issue by NeuroRookie** [GuyTeichman/RNAlysis#25]
When I run the gui, it turned out the error mentioned below:
>>> from rnalysis import gui
>>> gui.run_gui()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\LY_N\.conda\envs\rnaseq\lib\site-packages\rnalysis\gui\__init__.py", line 8, in run_gui
    main()
  File "C:\Users\LY_N\.conda\envs\rnaseq\lib\site-packages\rnalysis\gui\main.py", line 8, in main
    asyncio.run(gui.run())
  File "C:\Users\LY_N\.conda\envs\rnaseq\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\LY_N\.conda\envs\rnaseq\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\LY_N\.conda\envs\rnaseq\lib\site-packages\rnalysis\gui\gui.py", line 4337, in run
    if io.check_changed_version():
  File "C:\Users\LY_N\.conda\envs\rnaseq\lib\site-packages\rnalysis\utils\io.py", line 162, in check_changed_version
    with open(filename, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LY_N\\AppData\\Roaming\\RNAlysis\\RNAlysis\\latest_version.txt'

**Comment by GuyTeichman** [comment]
Hi NeuroRookie,
Thanks for spotting this bug!
It should be fixed in the next release of RNAlysis within a couple of days. 

In the meantime, to be able to run RNAlysis on your machine, please create the following directory on your computer:
`C:\Users\LY_N\AppData\Roaming\RNAlysis\RNAlysis`
(Go to the folder`C:\Users\LY_N\AppData\Roaming`, create a folder called `RNAlysis`, enter that folder, and create inside it another folder called `RNAlysis`). 
You should then be able to open RNAlysis and run it normally. 

Please let me know if that works for you, and if it doesn't then we will figure out another solution. 

Best,
Guy.

**Comment by NeuroRookie** [comment]
Thanks a lot! It is able to run now, but it tells me: The RNAlysis "reports" module is not installed.

**Comment by GuyTeichman** [comment]
Hi,
Did you install RNAlysis using pip, or are you using the stand-alone app?

**Comment by GuyTeichman** [comment]
Hi,
is it possible that you installed RNAlysis using the command `pip install RNAlysis`, instead of `pip install RNAlysis[all]`?
The command `pip install RNAlysis` installs only the basic features of RNAlysis, without any of the optional features (which can sometimes cause issues for some people). 

Please try re-installing RNAlysis and let me know if that works.

**Comment by NeuroRookie** [comment]
Hi,
Thanks a lot! It works well now.
