### ISSUE TITLE
Need assistance in running DESeq2 

### ISSUE THREAD

**Issue by Rajeshwarira** [GuyTeichman/RNAlysis#26]
### Describe the bug

Hello Guy,
I tried to run DESeq2 and I'm getting the following error
Traceback (most recent call last):

  File "rnalysis\gui\gui.py", line 3697, in finish_generic_job

  File "rnalysis\gui\gui_widgets.py", line 329, in run

  File "rnalysis\filtering.py", line 2874, in differential_expression_deseq2

  File "rnalysis\utils\differential_expression.py", line 130, in run_deseq2_analysis

  File "rnalysis\utils\io.py", line 1397, in run_r_script

AssertionError: R script failed to execute (return code 1).

### Steps To Reproduce

I need help to get over the error mentioned above.
Please do help me with this.

### How did you install RNAlysis?

Stand-alone app

### RNAlysis version

3.7

### Operating system

Windows

**Comment by GuyTeichman** [comment]
Hi,
To be able to figure out why your differential expression analysis failed, you will need to provide more details: what design matrix were you using? What was printed to your log box? Do you have R installed on your computer?
