### ISSUE TITLE
Unable to run rnalysis-gui from a non root user in an HPC cluster.  

### ISSUE THREAD

**Issue by urielrosen1981** [GuyTeichman/RNAlysis#31]
### Describe the bug

Hi,

I installed rnalysis using "pip install RNAlysis[all]" on a linux machine / on docker ubuntu container and
when trying to load rnalysis using rnalysis-gui /gui.run_gui() it hangs with no error.
It did work on some occasions on a docker container only when run from the root user which isn't
an option since we need to run the program as a regular user on the cluster .
any suggestions on how to debug this problem ?

### Steps To Reproduce

  singularity exec  --writable /data/bin/singularity_images/python_RNAlysis1.sif /bin/bash
INFO:    Converting SIF file to temporary sandbox...
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
Singularity> python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rnalysis import gui
Warning: 'GraphViz' installation not found. If you want to generate Ontology and Pathway Graphs, Please install GraphViz and add it to PATH.
See https://graphviz.org/download/ for more information.
>>> gui.run_gui()

### Screenshots

![image](https://github.com/GuyTeichman/RNAlysis/assets/103381200/f469398d-d5d1-4f91-aef7-06d104e372ec)

### How did you install RNAlysis?

installed via pip/Python

### RNAlysis version

3.10

### Operating system

Rocky linux \ docker container of ubuntu

**Comment by GuyTeichman** [comment]
Hi Uriel,
Unfortunately I don't have a lot of experience running RNAlysis on clusters, but I do have a few suggestions:

1. Is possible that your container is missing some of the dependencies required for running GUI programs? See the following table by Qt:
https://doc.qt.io/qt-5/linux-requirements.html
or the following list (for Ubuntu, but similar packages may exist for Rocky):
https://forum.image.sc/t/running-ilastik-gui-from-a-container/33477/2

2. root may need to give other users permission to access the display using the 'xhost' command. See the following answer:
https://unix.stackexchange.com/a/108787

Please let me know if any of these work for you, or if we need to dig deeper. 

Best,
Guy.

**Comment by urielrosen1981** [comment]
Hi ,

I examined your suggestion regarding xhost , but this did not help ,
QT libraries were properly installed , I tested rnalysis-gui outside the cluster environment with same result .
I will add more details that might help clarify the issue ,
when running "gui.run_gui()"  it hangs if I try to exit the session I see the following error  

![image](https://github.com/GuyTeichman/RNAlysis/assets/103381200/5c9150dc-7445-4591-998e-e90e85b5c20b)

please tell me if you have a way to debug this .

**Comment by GuyTeichman** [comment]
Hi,
A follow-up question:

When you exit the session after run_gui hangs, do you always get an error pointing to the same part of the code (file "gui_windows.py", line 1011, in update_time)?

If so, it may be an issue with one of the newer updates to the GUI. 
Could you please try installing an old version of RNAlysis (specifically version 3.5.2) by using "pip install RNAlysis==3.5.2", and seeing if you run into the same issue?
(make sure to uninstall the previous version before installing that one). 

Alternatively, could you please try installing RNAlysis on Python3.11 instead of Python 3.10? 

Best,
Guy.

**Comment by urielrosen1981** [comment]
on python 3.10:

 python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rnalysis import gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/rnalysis/gui/__init__.py", line 4, in <module>
    from .main import main
  File "/usr/local/lib/python3.10/dist-packages/rnalysis/gui/main.py", line 3, in <module>
    from rnalysis.gui import gui
  File "/usr/local/lib/python3.10/dist-packages/rnalysis/gui/gui.py", line 23, in <module>
    from rnalysis import fastq, filtering, enrichment, __version__
  File "/usr/local/lib/python3.10/dist-packages/rnalysis/fastq.py", line 14, in <module>
    from cutadapt.__main__ import main as cutadapt_main
ImportError: cannot import name 'main' from 'cutadapt.__main__' (/usr/local/lib/python3.10/dist-packages/cutadapt/__main__.py)


on python 3.11 it hangs :

python3.11
Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rnalysis import gui
Warning: 'GraphViz' installation not found. If you want to generate Ontology and Pathway Graphs, Please install GraphViz and add it to PATH.
See https://graphviz.org/download/ for more information.


any suggestions ?

**Comment by GuyTeichman** [comment]
The issue on python3.10 seems to related to having multiple python versions installed on the cluster. 

Regarding python3.11 - did you try installing RNAlysis version 3.5.2?

**Comment by urielrosen1981** [comment]
Hi ,

with python 3.11 trying to install version 3.5.2 , I get the below error 


pip install RNAlysis==3.5.2
ERROR: Ignored the following versions that require a different python version: 3.4.0 Requires-Python >=3.7, <3.11; 3.4.1 Requires-Python >=3.7, <3.11; 3.4.2 Requires-Python >=3.7, <3.11; 3.5.0 Requires-Python >=3.7, <3.11; 3.5.1 Requires-Python >=3.7, <3.11; 3.5.2 Requires-Python >=3.7, <3.11; 3.6.0 Requires-Python >=3.7, <3.11; 3.6.1 Requires-Python >=3.7, <3.11; 3.6.2 Requires-Python >=3.7, <3.11; 3.7.0 Requires-Python >=3.7, <3.11
ERROR: Could not find a version that satisfies the requirement RNAlysis==3.5.2 (from versions: 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.3.0, 3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.10.0)
ERROR: No matching distribution found for RNAlysis==3.5.2

**Comment by GuyTeichman** [comment]
I'm sorry, that's my bad, back then RNAlysis 3.5.2 did not yet support Python 3.11, so you would need to install it on Python 3.10 or lower.
