### ISSUE TITLE
Bug Report: PCA analysis, ValueError: Data must not be constant

### ISSUE THREAD

**Issue by Mitchzw** [GuyTeichman/RNAlysis#33]
### Describe the bug

Hey,

I tried to run a PCA plot but I get this error message:

Traceback (most recent call last):
  File "rnalysis/gui/gui.py", line 1347, in apply_function
  File "rnalysis/gui/gui.py", line 1970, in _apply_function_from_params
  File "rnalysis/gui/gui.py", line 1356, in _apply_function_from_params
  File "rnalysis/filtering.py", line 4401, in pca
  File "rnalysis/utils/generic.py", line 71, in standard_box_cox
  File "sklearn/utils/_set_output.py", line 142, in wrapped
  File "sklearn/preprocessing/_data.py", line 3103, in fit_transform
  File "sklearn/preprocessing/_data.py", line 3116, in _fit
  File "sklearn/preprocessing/_data.py", line 3116, in <listcomp>
  File "sklearn/preprocessing/_data.py", line 3274, in _box_cox_optimize
  File "scipy/stats/_morestats.py", line 1099, in boxcox
ValueError: Data must not be constant.

Here is the header of my data file:
[head.csv](https://github.com/GuyTeichman/RNAlysis/files/13849168/head.csv)

I have seen that your Celegans file from the tutorial has no 0 but extremely small values. Is this the problem?

### Steps To Reproduce

Loaded file
Visualize
Principal Component Analysis (PCA) plot
Apply

### How did you install RNAlysis?

Stand-alone app

### RNAlysis version

3.6.0

### Operating system

MacOS 12.7

**Comment by GuyTeichman** [comment]
Yes - before running PCA, you should filter your data to remove unexpressed/lowly-expressed genes.
