### ISSUE TITLE
Bug Report: Translate gene IDs, FileNotFoundError

### ISSUE THREAD

**Issue by Mitchzw** [GuyTeichman/RNAlysis#34]
### Describe the bug

Hey.

I want to translate the ensemble gene names into UniProit names but I get this error:

Traceback (most recent call last):
  File "rnalysis/gui/gui.py", line 2554, in redo
  File "rnalysis/gui/gui.py", line 2539, in redo
  File "rnalysis/gui/gui.py", line 1970, in _apply_function_from_params
  File "rnalysis/gui/gui.py", line 1356, in _apply_function_from_params
  File "rnalysis/filtering.py", line 392, in translate_gene_ids
  File "rnalysis/utils/io.py", line 1039, in map_gene_ids
  File "rnalysis/utils/io.py", line 1250, in _get_id_abbreviation_dicts
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/6h/vt6qqj_n7s983x66mn0q_d9h0000gn/T/_MEI0jL4t9/rnalysis/utils/../data_files/uniprot_dataset_abbreviation_dict.json'

Here is the shortened file I used for this:
[head.csv](https://github.com/GuyTeichman/RNAlysis/files/13849204/head.csv)

Is my RNAlysis installation missing data?

### Steps To Reproduce

loaded table
general
translate gene IDs
- translate to UniProtKB AC/ID
- translate from Ensembl

(I also tried other translate to and also auto for translate from. As far as I can see the error message is always the same)

### How did you install RNAlysis?

Stand-alone app

### RNAlysis version

3.6.0

### Operating system

MacOS 12.7

**Comment by GuyTeichman** [comment]
Hi,
please try running this again using the latest version of RNAlysis (V3.11.0) and let me know if it works. 

Best,
Guy.
