### ISSUE TITLE
Bug Report: Kallisto quantification of fastq failed

### ISSUE THREAD

**Issue by santataRU** [GuyTeichman/RNAlysis#42]
### Describe the bug

After I clicked "Start Kallisto quantify (paired-end reads)", I encountered the error message below: 

Traceback (most recent call last):
  File "rnalysis/gui/gui.py", line 4470, in finish_generic_job
  File "rnalysis/gui/gui_widgets.py", line 387, in run
  File "rnalysis/fastq.py", line 1920, in kallisto_quantify_paired_end
  File "rnalysis/fastq.py", line 1925, in _process_kallisto_outputs
  File "rnalysis/fastq.py", line 1995, in _merge_kallisto_outputs
FileNotFoundError: Could not find the kallisto output for sample '1-ctrlKO' at /Volumes/Xiao/RNAseq/202303_DDX42KO_RNAseq/trim_adapter/trim_fastq/kallisto/1-ctrlKO/abundance.tsv

### Steps To Reproduce

After I clicked "Start Kallisto quantify (paired-end reads)", I encountered the error message above. 

### Screenshots

![Screenshot 2024-11-06 at 11 26 33 PM](https://github.com/user-attachments/assets/6efed371-9696-4480-b293-111f78b12482)

### How did you install RNAlysis?

Stand-alone app

### RNAlysis version

4.1.0

### Operating system

MacOS

**Comment by santataRU** [comment]
> Hi, could you please show me the log box output (at the bottom of the RNAlysis window), as well as the kallisto log file itself (should be saved in our output directory)?
> 
> Thanks, Guy.

Thank you Guy,

There is no log from Kallisto. 

RNAlysis Log:
Welcome to RNAlysis!
Report generation turned off.

Window popped up for Error message:

RNAlysis has encountered the following error:

RNAlysis could not run '['/Users/bieniaszlab/opt/miniconda3/bin/kallisto/kallisto', 'version']'. Please ensure that the installed version of kallisto matches your operating system and try again. 


Traceback (most recent call last):
  File "rnalysis/utils/io.py", line 2456, in generate_base_call
  File "rnalysis/utils/io.py", line 2397, in run_subprocess
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1955, in _execute_child
NotADirectoryError: [Errno 20] Not a directory: '/Users/bieniaszlab/opt/miniconda3/bin/kallisto/kallisto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rnalysis/gui/gui.py", line 4470, in finish_generic_job
  File "rnalysis/gui/gui_widgets.py", line 387, in run
  File "rnalysis/fastq.py", line 1891, in kallisto_quantify_paired_end
  File "rnalysis/fastq.py", line 1952, in _parse_kallisto_misc_args
  File "rnalysis/utils/io.py", line 2463, in generate_base_call
OSError: RNAlysis could not run '['/Users/bieniaszlab/opt/miniconda3/bin/kallisto/kallisto', 'version']'. 
Please ensure that the installed version of kallisto matches your operating system and try again. 


In the MacOS terminal, if I run: Kallisto, I got the following:

kallisto 0.51.0

Usage: kallisto <CMD> [arguments] ..

Where <CMD> can be one of:

    index         Builds a kallisto index 
    quant         Runs the quantification algorithm 
    quant-tcc     Runs quantification on transcript-compatibility counts
    bus           Generate BUS files for single-cell data 
    h5dump        Converts HDF5-formatted results to plaintext
    inspect       Inspects and gives information about an index
    version       Prints version information
    cite          Prints citation information

Running kallisto <CMD> without arguments prints usage information for <CMD>
