### ISSUE TITLE
Bug Report: ModuleNotFoundError: No module named 'jdk'

### ISSUE THREAD

**Issue by kbipinkumar** [GuyTeichman/RNAlysis#43]
### Describe the bug

while attempting to launch rnalysis gui under archlinux i am getting following output

```bash
> rnalysis-gui 
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/rnalysis/gui/main.py", line 13, in <module>
    from rnalysis.gui import gui
  File "/usr/lib/python3.13/site-packages/rnalysis/gui/gui.py", line 25, in <module>
    from rnalysis import fastq, filtering, enrichment, __version__
  File "/usr/lib/python3.13/site-packages/rnalysis/fastq.py", line 22, in <module>
    from rnalysis import filtering
  File "/usr/lib/python3.13/site-packages/rnalysis/filtering.py", line 31, in <module>
    from rnalysis.utils import clustering, generic, ontology, settings, validation, differential_expression, \
        param_typing, genome_annotation
  File "/usr/lib/python3.13/site-packages/rnalysis/utils/differential_expression.py", line 11, in <module>
    from rnalysis.utils import io, generic, installs, validation, parsing
  File "/usr/lib/python3.13/site-packages/rnalysis/utils/installs.py", line 10, in <module>
    import jdk
ModuleNotFoundError: No module named 'jdk'
```

my understanding is that this module is from `install-jdk` that installs jdk which in turn is needed for picard-tools. 

as part packaging rnalysis we can install openjdk and picard-tools as dependencies along with any other optional dependencies systemwide. therefore, there is no need to utils/installs.py script to be run while launching the gui

my question is there a way we can avoid this script being run so that rnalysis-gui can be initialised? hopefully this can be implemented by some command line switch option itself. 

### Steps To Reproduce

execute `rnalysis-gui` from any terminal program under archlinux

### Screenshots

![Screenshot_20241228_170356](https://github.com/user-attachments/assets/23534fbf-7820-40e2-8743-8e4a0ce81f0a)

### How did you install RNAlysis?

ArchLinux

### RNAlysis version

4.1.0

### Operating system

Linux

**Comment by GuyTeichman** [comment]
Hi,
Sorry for the delayed response. I could make install-jdk an optional dependency, and check for jdk/picard in PATH before attempting to install. 
If you think that solution can work, I could make a small release next week.

Best,
Guy.

**Comment by kbipinkumar** [comment]
> Hi, Sorry for the delayed response. I could make install-jdk an optional dependency, and check for jdk/picard in PATH before attempting to install. If you think that solution can work, I could make a small release next week.
> 
> Best, Guy.

even i was thinking on the same line. instead of calling `rnalysis-gui` directly it can be invoked via an executable shell script like this where we can export location of picard.jar file as installed by OS package manager

```bash
#!/usr/bin/env sh
export PICARD_JAR="/usr/share/picard/picard.jar"
rnalysis-gui
```
rnalysis installer.py in turn can detect any variable set by the wrapper script and disable install of modules appropriately. for instance in this case as the path of picard.jar is set installing of picard and jdk can be skipped as archlinux picard-tools will pull appropriate java dependencies at the time of installation.

**Comment by GuyTeichman** [comment]
Should be solved now - please let me know if this solution worked.

Best,
Guy.

**Comment by kbipinkumar** [comment]
Yeah, I am able to run 4.1.1 release without any issues.
