### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by rachel1414** [GuyTeichman/RNAlysis#8]
Hello, 

I am completely new to all things coding, so I am very excited to try RNAlysis. I believe that I have installed Python 3.8, pip, R 4.2.2, graphviz, and kallisto. The installation problem is probably on my end, but any advice would be appreciated.

% pip install RNAlysis[all]
zsh: no matches found: RNAlysis[all]

% pip install RNAlysis

Collecting RNAlysis
  Using cached RNAlysis-3.3.0-py3-none-any.whl (19.9 MB)
Collecting numpy>=1.21.4
  Using cached numpy-1.24.1-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
Collecting pandas>=1.3.5
  Using cached pandas-1.5.2-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
Collecting matplotlib<3.6.0,>=3.4.2
  Using cached matplotlib-3.5.3.tar.gz (35.2 MB)
  Preparing metadata (setup.py) ... done
Collecting seaborn>=0.11.2
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
Collecting statsmodels>=0.12.0
  Using cached statsmodels-0.13.5-cp311-cp311-macosx_11_0_arm64.whl (9.2 MB)
Collecting scikit-learn>=1.0.0
  Using cached scikit_learn-1.2.0-cp311-cp311-macosx_12_0_arm64.whl (8.3 MB)
Collecting grid-strategy>=0.0.1
  Using cached grid_strategy-0.0.1-py3-none-any.whl (11 kB)
Collecting pyyaml>=6.0
  Using cached PyYAML-6.0-cp311-cp311-macosx_11_0_arm64.whl (167 kB)
Collecting UpSetPlot>=0.6.1
  Using cached UpSetPlot-0.8.0.tar.gz (22 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib-venn>=0.11.7
  Using cached matplotlib-venn-0.11.7.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Collecting scipy>=1.7.2
  Using cached scipy-1.10.0-cp311-cp311-macosx_12_0_arm64.whl (28.7 MB)
Collecting scikit-learn-extra>=0.2.0
  Using cached scikit-learn-extra-0.2.0.tar.gz (813 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pairwisedist>=1.2.0
  Using cached pairwisedist-1.3.0-py2.py3-none-any.whl (14 kB)
Collecting requests>=2.24.0
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting graphviz>=0.19.1
  Using cached graphviz-0.20.1-py3-none-any.whl (47 kB)
Collecting joblib<1.2.0,>=1.1.0
  Using cached joblib-1.1.1-py2.py3-none-any.whl (309 kB)
Collecting tqdm>=4.64
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting appdirs>=1.4.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting typing-extensions>=4.4
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting PyQt5>=5.15.7
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t9/j5z223l15tv0dy_n6nt9jmq40000gn/T/pip-build-env-wqvha_ul/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t9/j5z223l15tv0dy_n6nt9jmq40000gn/T/pip-build-env-wqvha_ul/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/t9/j5z223l15tv0dy_n6nt9jmq40000gn/T/pip-build-env-wqvha_ul/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/t9/j5z223l15tv0dy_n6nt9jmq40000gn/T/pip-install-qw5gcyn6/pyqt5_8f6e333c4e11463398cca7cd19fe7ac2/project.py", line 69, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/t9/j5z223l15tv0dy_n6nt9jmq40000gn/T/pip-build-env-wqvha_ul/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/t9/j5z223l15tv0dy_n6nt9jmq40000gn/T/pip-build-env-wqvha_ul/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/t9/j5z223l15tv0dy_n6nt9jmq40000gn/T/pip-build-env-wqvha_ul/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

Thank you,
R

**Comment by GuyTeichman** [comment]
Hey R,
It looks to me like the "pip" command you are using belongs to a different version of Python (3.11), which is not yet supported by _RNAlysis_.
To solve your installation problem, we need to figure out where does your Python 3.8 installation points to.

To that end - what operating system are you using? And where did you

**Comment by rachel1414** [comment]
Hi Guy,

You were right! I needed to match the pip version (which was for 3.11) to python 3.8. Then I was able to install RNAlysis. It seems to be working correctly for now. Excited to try it out! Thanks again for the suggestion and for making this available to everyone.

Best,
R
